/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#006038",
        "primary-container": "#1f7a4d",
        "primary-fixed": "#9ef5be",
        "primary-fixed-dim": "#82d8a3",
        background: "#f3fbf6",
        surface: "#f3fbf6",
        "surface-container": "#e8f0eb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#edf5f1",
        "surface-container-high": "#e2eae5",
        "surface-container-highest": "#dce4e0",
        "surface-variant": "#dce4e0",
        "on-background": "#161d1a",
        "on-surface": "#161d1a",
        "on-surface-variant": "#3f4941",
        "on-primary-container": "#aeffca",
        "on-secondary-container": "#406b5a",
        secondary: "#3b6756",
        "secondary-container": "#bbead4",
        success: "#2EAD66",
        warning: "#F5C542",
        outline: "#6f7a71",
        "outline-variant": "#bec9bf",
        "text-muted": "#6B7A70",
      },
      spacing: {
        "stack-space": "12px",
        "card-padding": "24px",
        "page-padding": "20px",
        "section-gap-md": "32px",
        "section-gap-sm": "16px",
        "inline-space": "8px",
        "section-gap-lg": "48px",
      },
      fontFamily: {
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "button-text": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "title-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "button-text": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "title-lg": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
