/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#006038",
        "primary-container": "#1f7a4d",
        "primary-fixed": "#9ef5be",
        "primary-fixed-dim": "#82d8a3",
        "on-primary": "#ffffff",
        "on-primary-container": "#aeffca",
        "on-primary-fixed": "#002110",
        "on-primary-fixed-variant": "#00522f",
        "inverse-primary": "#82d8a3",
        secondary: "#3b6756",
        "secondary-container": "#bbead4",
        "secondary-fixed": "#beedd7",
        "secondary-fixed-dim": "#a2d1bb",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#406b5a",
        "on-secondary-fixed": "#002116",
        "on-secondary-fixed-variant": "#234f3f",
        tertiary: "#44584d",
        "tertiary-container": "#5c7065",
        "tertiary-fixed": "#d2e8da",
        "tertiary-fixed-dim": "#b6ccbe",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ddf3e5",
        "on-tertiary-fixed": "#0d1f17",
        "on-tertiary-fixed-variant": "#384b41",
        background: "#f3fbf6",
        "background-mint": "#F3FBF6",
        "background-warm": "#F7F5EF",
        "on-background": "#161d1a",
        surface: "#f3fbf6",
        "surface-dim": "#d4dcd7",
        "surface-bright": "#f3fbf6",
        "surface-container": "#e8f0eb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#edf5f1",
        "surface-container-high": "#e2eae5",
        "surface-container-highest": "#dce4e0",
        "surface-variant": "#dce4e0",
        "surface-tint": "#066c41",
        "on-surface": "#161d1a",
        "on-surface-variant": "#3f4941",
        "inverse-surface": "#2a322f",
        "inverse-on-surface": "#ebf3ee",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        success: "#2EAD66",
        warning: "#F5C542",
        outline: "#6f7a71",
        "outline-variant": "#bec9bf",
        "text-muted": "#6B7A70",
        "text-dark": "#10251B",
        white: "#FFFFFF",
      },
      spacing: {
        "stack-space": "12px",
        "card-padding": "24px",
        "page-padding": "20px",
        "section-gap-md": "32px",
        "section-gap-sm": "16px",
        "inline-space": "8px",
        "section-gap-lg": "48px",
      },
      fontFamily: {
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "button-text": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "title-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "button-text": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "title-lg": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      borderRadius: {
        "4xl": "2rem",
      },
    },
  },
  plugins: [],
}
